# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TEST

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'getautoclicker'   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './build'  # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '18.x'                  # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: "@dhruv-techapps"
          cache: "npm"
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          cat –n build/static/js/*.js
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INLINE_RUNTIME_CHUNK: false
          GENERATE_SOURCEMAP: true
          REACT_APP_VARIANT: LOCAL
          PUBLIC_URL: "/"
          REACT_APP_GOOGLE_ANALYTICS_ID: ${{secrets.REACT_APP_GOOGLE_ANALYTICS_ID}}
          REACT_APP_GOOGLE_ADS_CLIENT: ${{secrets.REACT_APP_GOOGLE_ADS_CLIENT}}
          REACT_APP_GOOGLE_ADS_SLOT: ${{secrets.REACT_APP_GOOGLE_ADS_SLOT}}
          #Chrome Extension
          REACT_APP_CHROME_EXTENSION_ID: blfahkipmbikdeipdaogkjggbmgbippe
          #Edge Extension
          REACT_APP_EDGE_EXTENSION_ID: pmckiknbinanfnmbichcncmfpbcfpocn
          #i18n
          REACT_APP_I18N: https://raw.githubusercontent.com/Dhruv-Techapps/acf-i18n/main/locales
        
